# Generated by Django 4.2 on 2023-04-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_coef', models.FloatField(default=0.5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommendations.category')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='categories'
        ),
        migrations.AddField(
            model_name='profile',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, through='account.UserPreferences',
                                         to='recommendations.category'),
        ),
    ]
